### ISSUE TITLE
Pause toggle doesn't show when using the new pause mode

### ISSUE THREAD

**Issue by wondermike221** [mushfikurr/overline-zebar#12]
Specifically the new pause mode added in 3.7 wm-toggle-pause
When using the old pause mode as configure below the pause button shows up fine in the top left corner
```
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']
```
When using the new pause mode as configure below it does not show up.
```
  - commands: ['wm-toggle-pause']
    bindings: ['alt+shift+p']
```
adding the following to TilingControl fixes it. Just right below the motion.div that handles the binding modes.
```
        {glazewm.isPaused && (
          <motion.div
            key="paused"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.15, ease: "easeInOut" }}
            exit={{ opacity:0 }}
            className="h-full"
          >
            <Button>Paused</Button>
          </motion.div>
        )}
```
Inspecting shows that it is using isPaused and does not show up in the binding modes array anymore [#955](https://github.com/glzr-io/glazewm/issues/955) seems to be about this but there isn't much discourse. I'm unsure if it should still show up in binding modes..
